[tool.poetry]
name = "kawapack"
version = "0.5.0"
description = "Utility for extracting Arknights assets"
authors = ["astral4 <88992929+astral4@users.noreply.github.com>"]
license = "AGPL-3.0-or-later"


[tool.poetry.dependencies]
python = "^3.11"
UnityPy = "^1.9.24"
Pillow = "^9.3.0"
pycryptodome = "^3.16.0"
pymongo = "^4.3.3"
lz4 = "4.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
